---
# handlers file for ansible-role-proftpd
- name: restart proftpd
  service:
    name: 'proftpd'
    state: restarted

- name: restart firewalld
  service:
    name: 'firewalld'
    state: restarted
